// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkg94Wo20NOs0yAU29-e6fmRj1p_Kpzyg',
    appId: '1:242020131627:web:703275b80b9a8073ae1b6e',
    messagingSenderId: '242020131627',
    projectId: 'citymap-54d38',
    authDomain: 'citymap-54d38.firebaseapp.com',
    storageBucket: 'citymap-54d38.appspot.com',
    measurementId: 'G-42P690JYYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_idohFhOXBsvIfI_AMJrfpPhf2S2uVI',
    appId: '1:242020131627:android:6b5b3954bebe7692ae1b6e',
    messagingSenderId: '242020131627',
    projectId: 'citymap-54d38',
    storageBucket: 'citymap-54d38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbauOdN91jjd6YjfdU1P-iuMkKqBXIGg',
    appId: '1:242020131627:ios:730bc1194131f3dbae1b6e',
    messagingSenderId: '242020131627',
    projectId: 'citymap-54d38',
    storageBucket: 'citymap-54d38.appspot.com',
    iosBundleId: 'com.example.cityMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkbauOdN91jjd6YjfdU1P-iuMkKqBXIGg',
    appId: '1:242020131627:ios:3caf9ad8f248c6f5ae1b6e',
    messagingSenderId: '242020131627',
    projectId: 'citymap-54d38',
    storageBucket: 'citymap-54d38.appspot.com',
    iosBundleId: 'com.example.cityMap.RunnerTests',
  );
}
